# Generated by Django 5.0.3 on 2024-04-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0006_veiculo_acessorios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorios',
            options={'verbose_name': 'Acessorio', 'verbose_name_plural': 'Acessorios'},
        ),
    ]
